### ISSUE TITLE
Commit 9784e54 on master has a broken visualizer

### ISSUE THREAD

**Issue by eglassman** [lucasmf/refazer4education#65]
Even after npm installing and rebuilding, it believes the first or second step of execution is wrong, always.

**Comment by eglassman** [comment]
@ryosuzuki I'm not sure you can fix this if it works on your computer. :/ I'll assign myself as well.

**Comment by ryosuzuki** [comment]
Do you have a screenshot?

**Comment by eglassman** [comment]
No, because now the visualization button isn't working at all. When I click it I get this:
```
127.0.0.1 - - [05/Oct/2016 10:50:30] "GET /3/0/0?filter=None HTTP/1.1" 200 -
127.0.0.1 - - [05/Oct/2016 10:50:32] "GET /__webpack_hmr HTTP/1.1" 404 -
127.0.0.1 - - [05/Oct/2016 10:50:32] "POST /get_traces HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/eglassman/anaconda/lib/python3.5/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/eglassman/anaconda/lib/python3.5/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/eglassman/anaconda/lib/python3.5/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/eglassman/anaconda/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/eglassman/anaconda/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/eglassman/anaconda/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/eglassman/anaconda/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/eglassman/anaconda/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/eglassman/anaconda/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/eglassman/anaconda/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/eglassman/Documents/gitrepos/refazer4education/flaskr.py", line 864, in get_traces
    term = keywords[4]
IndexError: list index out of range
```

**Comment by eglassman** [comment]
![uiprototype_bug](https://cloud.githubusercontent.com/assets/2320194/19125604/9d131c06-8aec-11e6-83c9-2b82f13c5c31.jpg)

**Comment by ryosuzuki** [comment]
Yeah, this is a known issue. I also noticed that some clusters may not work well with the divergent strategy... 
But, you can see the traces by manually changing the step with the slider.

**Comment by eglassman** [comment]
The Visualizer button stopped working during our playtest today. I clicked on it and nothing happened.

**Comment by ryosuzuki** [comment]
@eglassman Could you replicate the error? I'd like to know where the error comes from.

**Comment by eglassman** [comment]
Object {before: "def product(n, term):↵    total, i = 1, 0↵    whil… total *= term(i)↵        i += 1↵    return total", after: "def product(n, term):↵    total, i = 1, 1↵    whil… total *= term(i)↵        i += 1↵    return total", test: "product(3, identity) "}
jquery.js:8630 POST http://glacial-harbor-46592.herokuapp.com/get_traces 500 (INTERNAL SERVER ERROR)

The first cluster in http://glacial-harbor-46592.herokuapp.com/3/0/0?filter=None also does not work when we click it. Nothing happens, for the same reason.
